name: Publish SDK to CocoaPods

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install Cocoapods
        run: gem install cocoapods

      # - name: Deploy to Cocoapods
      #   run: |
      #     set -eo pipefail
      #     pod lib lint --allow-warnings
      #     pod trunk push --allow-warnings
      #   env:
      #     COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
