name: Pull Request Build and Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    macos-build:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2
            - name: Build (macOS)
              run: swift build -v
            - name: Run tests
              run: swift test -v

    ubuntu-build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Build (Ubuntu)
              run: swift build -v
            - name: Run tests
              run: swift test -v
