name: Pull Request Build and Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
        strategy:
          matrix:
            os: [ubuntu-latest, macos-latest]
            swift: ["5.10", "6.0"]
        runs-on: ${{ matrix.os }}
        steps:
        - uses: swift-actions/setup-swift@next
          with:
            swift-version: ${{ matrix.swift }}
        - uses: actions/checkout@v5
        - name: Build
          run: swift build
        - name: Run tests
          run: swift test

    swift-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Run SwiftLint
              uses: norio-nomura/action-swiftlint@3.2.1
              # TODO: enable these settings:
              # env:
              #     DIFF_BASE: ${{ github.base_ref }}
              # with:
              #     args: --strict
