name: Pull Request Build and Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    macos-build:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2
            - name: Build (macOS)
              run: swift build -v
            - name: Run tests
              run: swift test -v

    ubuntu-build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Build (Ubuntu)
              run: swift build -v
            - name: Run tests
              run: swift test -v

    swift-lint:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Run SwiftLint
              uses: norio-nomura/action-swiftlint@3.2.1
              # TODO: enable these settings:
              # env:
              #     DIFF_BASE: ${{ github.base_ref }}
              # with:
              #     args: --strict
